on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master



name: renderbook

jobs:
  bookdown:
    name: Render-Book
    runs-on: ubuntu-latest

    env:
      RENV_PATHS_ROOT: ~/.cache/R/renv

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.1.2'
          use-public-rspm: true

      - name: Setup pandoc
        uses: r-lib/actions/setup-pandoc@v2
        with:
          pandoc-version: '2.17.1.1'

      - name: Install TinyTeX
        uses: r-lib/actions/setup-tinytex@v2
        env:
          # install full prebuilt version
          TINYTEX_INSTALLER: TinyTeX

      - name: Install missing system dependencies
        if: runner.os == 'Linux'
        run: |
          sudo apt-get install -y libgtk2.0-dev asymptote
          sudo apt-get install libcurl4-openssl-dev

      - name: Cache renv
        uses: actions/cache@v3
        with:
          path: ${{ env.RENV_PATHS_ROOT }}
          key: ${{ runner.os }}-renv-${{ hashFiles('**/renv.lock') }}
          restore-keys: ${{ runner.os }}-renv-

      - name: Restore packages
        shell: Rscript {0}
        run: |
          if (!requireNamespace("renv", quietly = TRUE)) install.packages("renv")
          renv::restore()

      - name: Install phantomjs
        run: |
          webshot::install_phantomjs()
        shell: Rscript {0}

      - name: Run Targets
        shell: Rscript {0}
        run: |
          install.packages('igraph') # fix issue dyn.load
          targets::tar_make(script = "analysis/targets-workflow.R", store = "analysis/_targets")

      - name: Render Book
        run: Rscript -e 'rmarkdown::render_site(encoding = "UTF-8")'

      - uses: actions/upload-artifact@v1
        with:
          name: _book
          path: _book/

# Need to first create an empty gh-pages branch
# see https://pkgdown.r-lib.org/reference/deploy_site_github.html
# and also add secrets for a GH_PAT and EMAIL to the repository
# gh-action from Cecilapp/GitHub-Pages-deploy
  checkout-and-deploy:
   if: github.event_name == 'push'
   runs-on: ubuntu-latest
   needs: bookdown
   steps:
     - name: Checkout
       uses: actions/checkout@master
     - name: Download artifact
       uses: actions/download-artifact@v1.0.0
       with:
         # Artifact name
         name: _book # optional
         # Destination path
         path: _site # optional
     - name: Deploy to GitHub Pages
       uses: Cecilapp/GitHub-Pages-deploy@v3
       env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
       with:
         email: ${{ secrets.EMAIL }}
         build_dir: _site/


